# Generated by Django 2.0.2 on 2019-03-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='name',
            field=models.CharField(default='hari', max_length=50),
            preserve_default=False,
        ),
    ]
